# Generated by Django 6.0.2 on 2026-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('n_of_correct', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
