# Generated by Django 6.0.2 on 2026-02-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequiz',
            name='correct_answer',
            field=models.CharField(default='enter some text...', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choicequiz',
            name='wrong_option_1',
            field=models.CharField(default='enter some text', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choicequiz',
            name='wrong_option_2',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='choicequiz',
            name='wrong_option_3',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
